### ISSUE TITLE
WebView does not load in 5.0.12 version of the app

### ISSUE THREAD

**Issue by avikchaks** [Zaarrg/stremio-desktop-v5#19]
**Describe the bug**
WebView does not load in 5.0.12 version of the app 

**To Reproduce**
Install the 5.0.12 version of the app and wait for it load 

**Expected behavior**
Application should load , it was working with the last version

**Screenshots and Videos**
![Image](https://github.com/user-attachments/assets/42c43f7a-cbc1-4241-b431-9686d4a2b38c)

**Logs and Errors:**
[21:17:20] [WEBVIEW]: Failed to create Web View in time, make sure WebView2 runtime is installed or provide a portable WebView2 runtime exe in portable_config/EdgeWebView. Check for potential errors in portable_config/errors-{date}.txt
[21:18:22] [WEBVIEW]: Web page could not be loaded after multiple attempts.

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - GPU: using Intel integrated graphics
 - Driver: 
 - App Version  5.0.0-beta.12

**Additional context**
Last night the previous version was working fine

**Comment by Zaarrg** [comment]
Sorry about that, probably related to a fix i added for this [issue](https://github.com/Zaarrg/stremio-desktop-v5/issues/7).

Can u test [this](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12) potential fixed version. [Direct-Download](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.12-x64-potential-fix.exe).

**Comment by Zaarrg** [comment]
Okay should now be fixed in [5.0.13](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.13) release.
Would appreciated if you could check.

**Comment by Ryukotsuki** [comment]
> Okay should now be fixed in [5.0.13](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.13) release. Would appreciated if you could check.

I am getting this error in the newest version on the very first open it works but as soon as I close it and try to open it, the error is back.

**Comment by Ryukotsuki** [comment]
[18:53:00] [WEBVIEW]: Failed to create Web View in time, make sure WebView2 runtime is installed or provide a portable WebView2 runtime exe in portable_config/EdgeWebView. Check for potential errors in portable_config/errors-{date}.txt

**Comment by Ryukotsuki** [comment]
I managed to get the installer version working, so I assume the issue is with the portable version.

**Comment by Zaarrg** [comment]
Yeah mb, i think i made some too quick choices to fix it quickly instead of properly. [This version](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12) now should fix it properly. Would appreciate if you could confirm that if it works for you with that version.

**Comment by Ryukotsuki** [comment]
> Yeah mb, i think i made some too quick choices to fix it quickly instead of properly. [This version](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12) now should fix it properly. Would appreciate if you could confirm that if it works for you with that version.

This is the installer version but I installed it anyway and then copied the files to my portable folder and it is working fine.

**Comment by Zaarrg** [comment]
ah mb, but thanks for confirming.

**Comment by Ryukotsuki** [comment]
> ah mb, but thanks for confirming.

Okay, the issue is still happening sometimes lol like when I close the program and quit it from the taskbar and I try to open it again it happens and if I exit it again real quick and then try again it opens again normally.

**Comment by lukasvri** [comment]
for me 5.0.12 works but not 13 and EXPERIMENTAL version

**Comment by maisonaustyn** [comment]
Was working before for me and newest update broke it

**Comment by Zaarrg** [comment]
@lukasvri @maisonaustyn 
Yeah its very weird, so released [5.0.14](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.14) this should mostly fix it for most. 

It seems like its some kind of problem with webview2 runtime itself, as for example using the portable version which includes a fresh webview2 runtime install takes longer to start then usually on first start and also randomly after 15 starts or so hangs on boot and only fix is to close and open the app again. 

Will see if i can find the exact reason but for now it should work again with [5.0.14](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.14) as i added all the hotfixes that where in 5.0.12.

**Comment by maisonaustyn** [comment]
Switched over to the x86 portable version. Was using the x64 portable version before and everything is working fine now. Checked the x64 version and that does seem to be working now as well

No idea if the fresh install fixed it or the update itself. But otherwise all good now at least for me

Edit: Worked on a fresh install for 4 or 5 launches then broke again. Fixes again after a fresh install

**Comment by Ryukotsuki** [comment]
same issue [09:23:04] [WEBVIEW]: Web page could not be loaded after multiple attempts this portable version haven't tested the installer yet.

**Comment by lukasvri** [comment]
5.0.14 does not work for me

**Comment by avikchaks** [comment]
Sorry I was held up with multiple releases at work , I uninstalled the previous version and installed a fresh version of 5.0.14 , Issue is fixed for me .

**Comment by Ryukotsuki** [comment]
I have done a full fresh install of the installer version and portable the installer version the error occurs between like 10-50 tries so it works a lot better but for some reason, the portable barely works at all.

**Comment by Zaarrg** [comment]
Should now be fixed in latest [5.0.16](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.16) release. 


If still occurs this issue can be reopened if not already present, as this issue is a duplicate of [this](https://github.com/Zaarrg/stremio-desktop-v5/issues/7) issue
