### ISSUE TITLE
Webview controls ui freezing and unresponsive during start of playback

### ISSUE THREAD

**Issue by doas-ice** [Zaarrg/stremio-desktop-v5#60]
**Describe the bug**
Playing a new show or youtube video sometimes makes the player controls ui unresponsive. I first noticed the issue while streaming some anime using the torrentio addon. The first episode of the anime played fine but whenever the next episode started playing the player window froze and became unresponsive. During the time the episode continued playing in the background and the audio could be heard. But there was only the loading animation with the anime logo visible on screen.

I have encountered the bug in two different machines (Desktop with Nvidia gpu and Laptop with integrated AMD gpu). Even with a clean install with no addons, playing a youtube video also resulted in this bug. The only difference noticed when playing a youtube video is that instead of a fullscreen loading animation with the anime logo the default stremio loading animation. As a result the media was visible during playback.

**To Reproduce**
1. Open Stremio
2. Navigate to a youtube channel (for my case PewDiePie)
3. Play the first video on the list
4. The player controls froze but playback starts

**Expected behavior**
Player controls should behave normally and not become unresponsive

**Screenshots and Videos**

> Youtube with Clean Install  

![Youtube with Clean Install](https://github.com/user-attachments/assets/00ad80d6-7628-413a-968b-b257e600c20c)  

  
  

> Resizing the window did not resize the contents  

![Resizing the window did not resize the contents](https://github.com/user-attachments/assets/68d85550-da76-4427-811f-06a5ec70e0b0)  

  
  

> Anime 2nd Episode using Torrentio Addon (Note: The media is playing beacuse the audio could be heard. The fullscreen banner is still loading when taking the screenshot and thus partially visible.)  

![Anime 2nd Episode using Torrentio Addon](https://github.com/user-attachments/assets/4034498a-2d67-4d1d-bdb3-91ea3f35be50)  

**Logs and Errors:**
There are not error logs in ``%localAppData%\Programs\LNV\Stremio-5\portable_config``. I am attaching the logged output for stremio.
1. Youtube on Clean Install [stremio.log](https://github.com/user-attachments/files/18904496/stremio.log)
2. Anime with Torrentio (Froze during the start of second episode) [stremio-torrentio.log](https://github.com/user-attachments/files/18904510/stremio-torrentio.log)

**Desktop:**
 - OS: Windows 10
 - GPU: GTX 1650 Super
 - Driver: Game Ready Driver 572.42
 - App Version: 5.0.17 64bit

**Laptop:**
 - OS: Windows 11
 - GPU: Radeon RX Vega 7
 - Driver: 31.0.21910.4002
 - App Version: 5.0.17 64bit

**Additional context**
Whenever the player is frozen, moving or resizing the windows sometimes shows a glimpse of the mpv window playing the media underneath. Also resizing the windows does not resize the controls. Pressing Esc, F5 or Ctrl+F5 does nothing. Only Manually quitting the program from tray or killing from task manager works.

**Comment by Zaarrg** [comment]
@doas-ice 

Should now be fixed in **18.23**. Use **CTRL+F5** to refresh if on settings page the version is < 18.23.

Thanks for reporting, seems like my recent update that fixed thumbnails missing for animes like solo leveling broke it for catalogs from e.g. kitsu or yt. So sorry about that.

Would appreciate if you could confirm that it is now works for you as well.

**Comment by doas-ice** [comment]
@Zaarrg 

Thanks for the quick response. Unfortunately the issue is still present. The version shown on the settings page is 18.24 

![Settings Version](https://github.com/user-attachments/assets/f5aa42bb-16b5-4d3c-8644-7aaf73d194ee)

I also tested after deleting the `stremio.exe.WebView2` folder but the issue remains the same.


> Thanks for reporting, seems like my recent update that fixed thumbnails missing for animes like solo leveling broke it for catalogs from e.g. kitsu or yt. So sorry about that.

I'm sorry to say I don't quite understand the relationship between my issue and the update you've mentioned here. Maybe you are referencing my 3rd screenshot about the partially loaded thumbnail? If that is the case then I'd like to clarify the thumbnail was still slowly loading when I took the screenshot and I didn't wait for it to fully load.   

Nevertheless that is not core the issue I am trying to report here. I apologize if my post was not entirely clear. If you require further clarification about the issue I'll gladly provide them. Let me know if you need any screen recording or additional logs.

Also a very big thank you for your hard work on this project.

**Comment by Zaarrg** [comment]
@doas-ice 

Can u try disabling the toggle `Use mpv for external subs` and checking if that fixes it:

![Image](https://github.com/user-attachments/assets/534c0e9b-bcd0-4316-bfa9-948ab1cb5d5b)

The update i did caused the player to become like u described unresponsive when i tried watching using kitsu for solo leveling s2 so i fixed that (which also fixed yt for me as that was also unresponsive). Thought that was it. But i guess will check again.

**Comment by Jarvis636** [comment]
I too experience this @Zaarrg I don't see Use mpv for external subs on my settings this is version 18.21

**Comment by Zaarrg** [comment]
@Jarvis636 Refresh using CTRL + F5. 

I added the toggle in >= 18.24. So in 18.21 it will be missing like you mentioned

**Comment by doas-ice** [comment]
@Zaarrg 

Disabling `Use mpv for external subs` setting did not fix the issue for me. I played a youtube video it became unresponsive. 

From my testing it seems that this issue appears when the youtube channels videos are being played for the first time. If i kill/exit the process and try to play videos from that specific channel again the issue does not appear. 

In the case of Anime the first episode plays fine without any issues. But playing the next episode makes the player unresponsive. After restarting the program the 2nd episode plays fine but then the 3rd episode triggers the issue.

~Also is there a way to see the webview logs? It might be helpful to pinpoint the exact underlying issue.~

Edit: I accessed the webview2 console using `set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS=--auto-open-devtools-for-tabs` variable and the following error popped up in console

```
useVideo.js:53  ShellVideoWithHTMLSubtitlesWithStreamingServer 
(anonymous) @ StremioVideo.js:84
d @ useVideo.js:53
c @ useVideo.js:106
(anonymous) @ Player.js:228
I @ VolumeSlider.js:17
dr @ react-dom.production.min.js:160
CE @ react-dom.production.min.js:196
p_ @ react-dom.production.min.js:291
RT @ react-dom.production.min.js:279
cT @ react-dom.production.min.js:279
dT @ react-dom.production.min.js:279
_T @ react-dom.production.min.js:272
wo @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:266
```

![Image](https://github.com/user-attachments/assets/df22aa88-b02d-428d-a67d-44ca7f50d878)

**Comment by Jarvis636** [comment]
Yep this one is the worst it keeps freezing up

**Comment by Jarvis636** [comment]
I have to keep restarting it

**Comment by Zaarrg** [comment]
@doas-ice 

Do u have any subtitle addons or any specific torrentio settings ? 

Checked the logs u provided again it seems for some reason for playback its using the stremio server as the url starts with `http://127.0.0.1:11470/`. Checked what i get on my end on solo leveling and it uses torrentio directly like it normally should ` https://torrentio.strem.fun/`.

Also uploaded a version with enabled dev tools [here](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12) - [download](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.17-x64-debug.exe)

And what would help is when the error shows up in the dev tools console click on the `useVideo.js:53`, `Player.js:228` and `VolumeSlider.js:17` this should show what exact line of code is causing it, would help me to identify where exactly its happening. As the line number in the browser differ from the code.

Also can u try going into `Settings > Player > Audio` and set `Max Volume` to anything other then the default like 125.
As the error u provided suggest it might be caused by a invalid max volume number. 

Edit:
Also just did a update that possibly fixed it so use `CTRL+F5` to refresh so its the latest version. Should be version: **18.26**

**Comment by doas-ice** [comment]
@Zaarrg Thank you.

Looks like the recent commit fixed the issue. I did not encounter the error on the latest version `18.26`
